version: '3.8'

services:
  redis:
    image: redis:6
    container_name: my-redis
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - db

  db:
    image: postgres:latest
    container_name: my-data_base
    restart: always
    environment:
      - POSTGRES_USER=jesus
      - POSTGRES_PASSWORD=554316
      - POSTGRES_DB=my-data_base
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  nginx:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  postgres_data:
